# Generated by Django 3.1.13 on 2022-02-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_debug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAdvancedTabs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_name', models.CharField(max_length=10, null=True)),
                ('tab_name', models.CharField(max_length=50, null=True)),
                ('tab_text', models.TextField(null=True)),
                ('tab_functions', models.TextField(null=True)),
            ],
        ),
    ]
