# Generated by Django 3.1.13 on 2022-02-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dataadvancedtabs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataadvancedtabs',
            name='tab_functions',
            field=models.JSONField(null=True),
        ),
    ]
