# Generated by Django 3.1.13 on 2022-03-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dataadvancedtabs_tab_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAdvancedTabsManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_name', models.CharField(max_length=10, null=True)),
                ('manager_content', models.JSONField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dataadvancedtabs',
            name='at_name',
        ),
    ]
