# Generated by Django 3.1.13 on 2022-03-04 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220304_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataadvancedtabs',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.dataadvancedtabsmanager'),
        ),
        migrations.AlterField(
            model_name='dataadvancedtabsmanager',
            name='at_name',
            field=models.CharField(default='new', max_length=10, null=True),
        ),
    ]
