# Generated by Django 3.1.13 on 2022-03-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220304_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataadvancedtabs',
            name='tab_functions',
        ),
        migrations.RemoveField(
            model_name='dataadvancedtabs',
            name='tab_text',
        ),
        migrations.RemoveField(
            model_name='dataadvancedtabs',
            name='tab_title',
        ),
        migrations.AlterField(
            model_name='dataadvancedtabs',
            name='tab_name',
            field=models.CharField(default='tab', max_length=50, null=True),
        ),
    ]
