# Generated by Django 3.1.13 on 2022-05-08 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220314_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAdvancedTabsCustomization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_content', models.JSONField(null=True)),
                ('tab', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.dataadvancedtabs')),
            ],
        ),
    ]
