# Generated by Django 3.1.13 on 2022-06-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_dataadvancedtabscustomization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjectivesvalues',
            name='order',
            field=models.SmallIntegerField(blank=True, default=1),
        ),
    ]
