# Generated by Django 3.1.13 on 2022-06-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220616_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataadvancedtabs',
            options={'ordering': ['order'], 'verbose_name': 'DataAdvancedTabs', 'verbose_name_plural': 'DataAdvancedTabs'},
        ),
        migrations.AddField(
            model_name='dataadvancedtabs',
            name='order',
            field=models.SmallIntegerField(blank=True, default=1),
        ),
    ]
