# Generated by Django 3.1.13 on 2022-08-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220620_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataadvancedtabsmanager',
            name='at_name',
            field=models.CharField(default='new', max_length=50, null=True),
        ),
    ]
