# Generated by Django 3.1.13 on 2022-09-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220808_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAdvancedApps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='tab', max_length=50, null=True)),
                ('app_content', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'DataAdvancedApps',
                'verbose_name_plural': 'DataAdvancedApps',
            },
        ),
    ]
